config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'foods#index'
  resources :users do 
    resources :foods, only: [:index, :new, :create, :destroy]
    resources :receipts, only:[:index, :show, :new, :create, :destroy]  do
      get "/foods/:id/remove" => "receipts#remove_food", as: :remove_food
      get "/foods/add" => "receipts#add_food_view", as: :add_food_view
      post "/foods/add" => "receipts#add_food", as: :add_food
    end
    resources :publics, only:[:index]
    resources :shoppings, only:[:index]
  end

  resources :foods, only: [:index, :new, :create, :destroy]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Recipe, public: true

    return unless user.present?

    can :manage, Recipe, user_id: user.id
    can :manage, Food, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  validates :name, presence: true, length: { maximum: 25 }
  validates :measurement_unit, presence: true, length: { maximum: 5 }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/receipt.rb
class Receipt < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  validates :name, presence: true, length: { maximum: 25 }
  validates :description, presence: true, length: { maximum: 500 }

  def total_price
    recipe_foods.includes([:food]).inject(0) { |sum, recipe_food| sum + recipe_food.food.price }
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to : user
    has_many : recipe_foods, dependent: :destroy

    validates :name, presence: true, length: { minimum: 3, maximum: 50 }
    validates :description, presence: true, length: { minimum: 1, maximum: 500 }
    validates :preparation_time, presence: true, numericality: { only_float: true, greater_than: 0 }
    validates :cooking_time, presence: true, numericality: { only_float: true, greater_than: 0 }
    validates :public, inclusion: { in: [true, false] }
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :receipt
  belongs_to :food

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/shopping_item.rb
class ShoppingItem
  attr_accessor :required_quantity, :food

  def initialize(food, required_quantity)
    @food = food
    @required_quantity = required_quantity
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :foods, dependent: :destroy
  has_many :receipts, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @food = current_user.foods.all
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    @food.user = current_user
    if @food.save
      redirect_to foods_path
    else
      render :new
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to foods_path
  end

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/publics_controller.rb
class PublicsController < ApplicationController
  def index
    @publics = Receipt.includes(%i[user recipe_foods]).where(public: true).order(created_at: :desc)
  end
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @receipts = Receipt.includes([:user]).where(user: @user).or(Receipt.where(public: true))
  end

  def show
    @receipt = Receipt.find(params[:id])
  end

  def add_food_view
    @receipt = Receipt.find(params[:receipt_id])
    render 'add_food'
  end

  def add_food
    @receipt = Receipt.find(params[:receipt_id])
    @food = Food.find(params[:food_id])
    @receiptfood = RecipeFood.includes([:food]).new(quantity: params[:quantity], food: @food, receipt: @receipt)
    if @receiptfood.save
      redirect_to user_receipt_path(id: @receipt.id)
    else
      print @receiptfood
      render :new
    end
  end

  def remove_food
    @receipt = Receipt.find(params[:receipt_id])
    @food = RecipeFood.includes([:food]).find(params[:id])
    @receipt.recipe_foods.delete(@food)
    redirect_to user_receipt_path
  end

  def new
    @receipt = Receipt.new
    @user = current_user
  end

  def create
    @receipt = Receipt.new(receipt_params)
    @receipt.user = current_user
    print receipt_params
    if @receipt.save
      redirect_to user_receipts_path
    else
      print 'Failed to Save User'
      render :new
    end
  end

  def destroy
    @receipt = Receipt.find(params[:id])
    @receipt.destroy
    redirect_to user_receipts_path
  end

  def receipt_params
    params.require(:receipt).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    def index
    @recipes = Recipe.all
    end

    def show
    @recipe = Recipe.find(params[:id])
    end
end

app/controllers/shoppings_controller.rb
require_relative '../models/shopping_item'
class ShoppingsController < ApplicationController
  def index
    @shoppings = []
    @recipes = Receipt.all
    @recipes.each do |recipe|
      recipe.recipe_foods.includes([:food]).each do |recipe_food|
        if recipe_food.quantity > recipe_food.food.quantity
          shopping_item = ShoppingItem.new(recipe_food.food, recipe_food.quantity - recipe_food.food.quantity)
          @shoppings << shopping_item
        end
      end
    end

    @total_price = @shoppings.inject(0) do |sum, shopping_item|
      sum + (shopping_item.food.price * shopping_item.required_quantity)
    end
  end
end

app/controllers/users_controller.rb
class UserController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/publics_helper.rb
module PublicsHelper
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/helpers/shoppings_helper.rb
module ShoppingsHelper
end

app/views/foods/index.html.erb
<%= render '/menu' %>

<div class="add-f-button">
    <button class="button-af">
      <%= link_to "Add Food", new_food_path, {:class => "add_food_button"} %>
    </button>
</div>
<div class='index-container'>
      <table class="table-container">
        <thead>
          <tr>
            <th>Food</th>
            <th>Quantity</th>
            <th>Unit price</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
        <% @food.each do |food| %>
          <tr>
            <td><%= food.name %></td>
            <td> <%=food.quantity%> <%=food.measurement_unit %></td>
            <td>$ <%= food.price %></td>
            <td>
              <div>
                <%=button_to "Delete", {:controller => :foods, :action => 'destroy', :id => food.id}, :method => :delete, class: 'delete-button' %>
             </div>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
</div>

app/views/foods/new.html.erb
<div class='new_container'>
    <h1 class= 'title-f'>Add Food</h1>
    <%= form_with model: @food do |f| %>
      <%= f.label :name, class:'label-f' %></br>
      <%= f.text_field :name, class:'input-f'%></br>
      <%= f.label :measurement_unit, class:'label-f' %></br>
      <%= f.text_field :measurement_unit, class:'input-f' %></br>
      <%= f.label :price, class:'label-f' %></br>
      <%= f.number_field :price, step: 0.5, class:'input-f' %></br>
      <%= f.label :quantity, class:'label-f' %></br>
      <%= f.number_field :quantity, class:'input-f' %></br>
      <div class='dflex'>
        <div class="back--button">
          <button class="button-af">
            <%= f.submit "Add", class:'addi' %>
          </button>
        </div>

        <div class="back--button">
          <button class="button--bb">
            <%= link_to "Back to Food", user_foods_path(current_user), {:class => "ret-button"} %>
          </button>
        </div>
      </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/publics/index.html.erb
<%= render '/menu' %>

<div class="publics">
    <h2>Public Recipes</h2>
    <ul class="publics-list">
        <% @publics.each do |public|%>
            <li>
                <div class="label">
                    <h4><%= public.name%></h4>
                    <p> By: <%= public.user.name %></p>
                </div>
                <div class="details">
                    <p> Total Food Items : <%= public.recipe_foods.length %></p>
                    <p> Total Price : $ <%= public.total_price %></p>
                </div>
            </li>
        <%end%>
    <ul>
</div>

app/views/receipts/add_food.html.erb
<div class='new_container'>
    <h1 class= 'title-f'>Add Ingredient</h1>
  <%= form_tag('add', method: 'post') do  |f| %>
        <%= label_tag  :food_id, 'Food', class:'label-f' %></br>
        <%= select_tag  :food_id, options_from_collection_for_select(Food.all, "id", "name"), class:'input-f'   %></br>
        <%= label_tag :quantity, 'Quantity', class:'label-f' %></br>
        <%= number_field_tag :quantity, class:'input-f' %></br>
        <div class='dflex'>
        <div class="back--button">
          <button class="button-af">
            <%= submit_tag "Add", class:'addi' %>
          </button>
        </div>

        <div class="back--button">
          <button class="button--bb">
            <%= link_to "Back to Receipts", user_receipts_path(current_user), {:class => "ret-button"} %>
          </button>
        </div>
      </div>
    <% end %>
</div>

app/views/receipts/index.html.erb
<%= render '/menu' %>

<div class="recipes">
    <h2>Recipes</h2>

  <div class="add-f-button">
    <button class="button-af">
      <%= link_to "Add Recipe", new_user_receipt_path, {:class => "add_food_button"} %>
    </button>
  </div>

    <ul class="recipes-list">
        <% @receipts.each do |receipt| %>
            <li class="recipe">
                <div class="label">
                    <%= link_to user_receipt_path(id: receipt.id) do%>
                        <h4><%=receipt.name%></h4>
                    <%end%>
                    <%= button_to "REMOVE", user_receipt_path(id:receipt.id), method: :delete, class: 'delete-recipe' if receipt.user==@user%>
                </div>
                <div class="desc">
                    <p><%=receipt.description%></p>
                </div>
            </li>
        <%end%>
    </ul>
</div>

app/views/receipts/new.html.erb
<div class='new_container'>
    <h2 class= 'title-f'>Add Recipe</h2>
    <%= form_with model: @receipt, url: user_receipts_path(current_user)  do |f| %>
     <div class="field">
        <%= f.label :name, class:'label-f' %></br>
        <%= f.text_field :name, class:'input-f' %>
     </div>
    <div class="field">
        <%= f.label :description, class:'label-f' %>
        <%= f.text_area :description, class:'input-f' %>
    </div>
    <div class="field">
        <%= f.label :preparation_time, class:'label-f' %>
        <%= f.number_field :preparation_time, step: :any, class:'input-f' %>
    </div>
    <div class="field">
        <%= f.label :cooking_time, class:'label-f' %>
        <%= f.number_field :cooking_time, step: :any, class:'input-f' %>
    </div>

    <div class="public-field">
        <%= f.label :public, class:'label-f' %>
        <%= f.check_box :public %>
    </div>
    <div class='dflex'>
        <div class="back--button">
          <button class="button-af">
            <%= f.submit "Add", class:'addi' %>
          </button>
        </div>

        <div class="back--button">
          <button class="button--bb">
            <%= link_to "Back to Receipts", user_receipts_path(current_user), {:class => "ret-button"} %>
          </button>
        </div>
      </div>
    <% end %>
</div>

app/views/receipts/remove_food.html.erb
<p>Deleting Food from Recipe</p>

app/views/receipts/show.html.erb
<%= render '/menu' %>

<div class="recipe-details">
    <h2><%=@receipt.name%></h2>
    <div class="desc">
        <div class="text">
            <p>Preparation Time : <%= @receipt.preparation_time %></p>
            <p>Cooking Time : <%= @receipt.cooking_time %></p>
            <p><%=@receipt.description %></p>
        </div>
        <div class="actions">
            <label>Public</label>
            <%= check_box_tag 'isPublic', 'no', @receipt.public, class: "name" %>
        </div>
    </div>

  <div class='dflex-show'>
    <div class="add-g-button">
          <button class="button-g">
            <%= link_to "Generate shopping list", user_shoppings_path, {:class => "add_generate_button"} %>
          </button>
    </div>
    <div class="add-i-button">
          <button class="button-i">
            <%= link_to "Add Ingredient", user_receipt_add_food_path(receipt_id: @receipt.id), {:class => "add_ingredient_button"} %>
          </button>
    </div>
  </div>
    <hr/>

    <table>
        <thead>
            <tr>
                <th>Food</th>
                <th>Quantity</th>
                <th>Value</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <% @receipt.recipe_foods.each do |recipe_food| %>
                <tr>
                    <td><%= recipe_food.food.name %></td>
                    <td><%= recipe_food.quantity %> <%=recipe_food.food.measurement_unit%></td>
                    <td>$ <%= recipe_food.food.price * recipe_food.quantity %></td>
                    <td>
                        <%= link_to 'Modify', user_receipts_path%>
                        <%= link_to 'Remove', user_receipt_remove_food_path(receipt_id:@receipt.id,id:recipe_food.id), method: :delete %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/recipes/index.html.erb
<div class="container">
<% @recipes do |recipe| %>
    <%= recipe.name %> <br/>
<% end %>
</div>

app/views/shoppings/index.html.erb
<%= render '/menu' %>

<div class="shoppings">
  <h2 class='shop-title'>Shopping List</h2>
  <div class='flex-shop'>
    <h4 class='amount'>Amount of food items to buy:<span><%= @shoppings.length%></span></h4>
    <h4>Total value of food needed:<span>$<%=@total_price%></span></h4>
  </div>
  <table class='shop-table'>
          <thead>
            <tr>
              <th>Food</th>
              <th>Quantity</th>
              <th>Price</th>
            </tr>
          </thead>
          <tbody>
            <% @shoppings.each do |shopping| %>
              <tr>
                <td><%= shopping.food.name %></td>
                <td><%= shopping.required_quantity %> <%=shopping.food.measurement_unit%></td>
                <td>$<%= shopping.food.price * shopping.required_quantity%></td>
              </tr>
            <% end %>    
          </tbody>
    </table>
</div>